version: '3.7'
services: 
  prom:
    image: quay.io/prometheus/prometheus
    ports: 
      - 9090:9090
    volumes: 
      - ./conf:/conf
      - ./prometheus_data:/prometheus
    command: ["--config.file=/conf/prometheus.yml", "--storage.tsdb.retention=30d", "--web.enable-lifecycle"]
  db:
    image: mongo
    restart: always
    volumes: 
      - ./mongo_data:/data/db
  api:
    depends_on: 
      - db
    build: .
    ports: 
      - 5000:5000
    volumes: 
      - ./conf:/prom/conf
      - ./:/app